### ISSUE TITLE
[BUG] Invalid Status Code when trying to install mod

### ISSUE THREAD

**Issue by ChristopherHaws** [ModManagerMC/ModManager#143]
**Describe the bug**
I am trying to install "FPS Display" mod and I get a 403 HTTP status code error.

**To Reproduce**
1. Go to 'FPS Display' mod
2. Click on 'Install'

**Expected behavior**
The mod should download and install.

**Screenshots**
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/5934505/160268293-8a59fc15-bd60-4115-91bb-9cf9d813dc4e.png">

**Logs**
```shell
[22:35:27] [DefaultDispatcher-worker-3/INFO]: Installing FPS - Display v1.4.2+1.18.2
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: xyz.deathsgun.modmanager.api.http.HttpClient$InvalidStatusCodeException: Received invalid status code: 403
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.api.http.HttpClient.download(HttpClient.kt:48)
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.UpdateManager.installVersion(UpdateManager.kt:302)
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.UpdateManager.installVersion$default(UpdateManager.kt:282)
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.UpdateManager.installMod(UpdateManager.kt:273)
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.gui.ModProgressScreen.installMod(ModProgressScreen.kt:119)
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.gui.ModProgressScreen.access$installMod(ModProgressScreen.kt:39)
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.gui.ModProgressScreen$init$2.invokeSuspend(ModProgressScreen.kt:70)
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[22:35:28] [DefaultDispatcher-worker-3/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[22:35:28] [DefaultDispatcher-worker-3/ERROR]: modmanager.error.unknown.update
```

**Please complete the following information:**
 - OS: macOS 12.2.1 (M1 Max)
 - Minecraft version: 1.18.2
 - Version 1.2.3

**Comment by mbjd05** [comment]
Also happening for me on Windows 10.

**Comment by DeathsGun** [comment]
Looks like a bug in modrinth: https://twitter.com/modrinth/status/1508579194661396497?s=21&t=poGWs7BgP78yCRsY1QYNMA
