### ISSUE TITLE
when you update something, it's always an empty zip

### ISSUE THREAD

**Issue by KozumikkuDelta** [ModManagerMC/ModManager#151]
**Describe the bug**
every time i update a mod,
no matter which way
one by one or all at once they are always empty zips

**Please complete the following information:**

 - Windows 11
 - Minecraft version 1.18.2

Crash-report (if any):
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
![Captura de pantalla 2022-05-26 201801](https://user-images.githubusercontent.com/94224228/170615568-bf55291b-9374-4ae2-b787-189077c28389.png)

	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:146)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:146)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:210)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more
	Suppressed: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\Usuario\AppData\Roaming\.minecraft\mods\okzoomer-5.0.0-beta.6+1.18.2.jar]: java.util.zip.ZipException: zip file is empty
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
		at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
		at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:143)
		... 5 more
	Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\Usuario\AppData\Roaming\.minecraft\mods\okzoomer-5.0.0-beta.6+1.18.2.jar]: java.util.zip.ZipException: zip file is empty
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:255)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212)
		at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	Caused by: java.util.zip.ZipException: zip file is empty
		at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
		at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
		at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
		at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
		at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
		at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:280)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:250)
		... 7 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\Usuario\AppData\Roaming\.minecraft\mods\fabric-api-0.53.4+1.18.2.jar]: java.util.zip.ZipException: zip file is empty
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:143)
	... 5 more
Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\Usuario\AppData\Roaming\.minecraft\mods\fabric-api-0.53.4+1.18.2.jar]: java.util.zip.ZipException: zip file is empty
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:255)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:280)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:250)
	... 7 more

**Comment by DeathsGun** [comment]
Will be fixed with [Core#1](https://github.com/ModManagerMC/core/issues/1)
