### ISSUE TITLE
Invalid Status Code: 403 - While Attempting to Update Various Mods

### ISSUE THREAD

**Issue by Talbe1** [ModManagerMC/ModManager#152]
I use the ModManager frequently to update the mods that I have installed, I use the latest version of the mod that matches my game version (currently version 1.2.3 for Minecraft Fabric 1.18.2). When I attempt to update **various different** mods I get the same error message repeatedly (see picture).
![2022-05-27_14 12 18](https://user-images.githubusercontent.com/104154497/170692575-c66ab3a0-faf1-4fe8-8ad3-1b0f48067372.png)

The issue persists even if I tell it to try again. I tried checking if this issue still presists when I have Minecraft Fabric 1.18.2 (with Kotlin Fabric Language, 1.7.2 or 1.7.1, and the currently latest Fabric Loader version, 0.14.6, and latest Fabric API, 0.53.4) installed in the default location, and it still does.
After the error message appears I find an empty .jar file in my mods folder named after the new version of the mod ModManager attempted to update to (the file size is always 0 KB). If I try to relaunch the game, it will crash due to having an empty .jar file.

**Comment by Talbe1** [comment]
I checked if the Cloudflare DNS I have been using was the cause of my problem, as mentioned in #149. I switched to my ISP's DNS from the Cloudflare DNS, and despite that, the issue still persisted afterwards. Maybe the problem will eventually auto-solve itself. Here's the log of the issue:
[2022-05-28-5.log](https://github.com/ModManagerMC/ModManager/files/8790954/2022-05-28-5.log)

**Comment by DeathsGun** [comment]
Will be fixed with [Core#1](https://github.com/ModManagerMC/core/issues/1)

**Comment by TheoCGaming** [comment]
> I checked if the Cloudflare DNS I have been using was the cause of my problem, as mentioned in #149. I switched to my ISP's DNS from the Cloudflare DNS, and despite that, the issue still persisted afterwards. Maybe the problem will eventually auto-solve itself. Here's the log of the issue: [2022-05-28-5.log](https://github.com/ModManagerMC/ModManager/files/8790954/2022-05-28-5.log)

Here's the part you may be interested in @DeathsGun 
```
[13:13:57] [DefaultDispatcher-worker-2/INFO]: Updating Ok Zoomer
[13:13:57] [DefaultDispatcher-worker-2/INFO]: Error while deleting C:\Users\Lenovo\AppData\Roaming\.minecraft\mods\okzoomer-5.0.0-beta.5+1.18.2.jar trying on restart again
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: xyz.deathsgun.modmanager.api.http.HttpClient$InvalidStatusCodeException: Received invalid status code: 403
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.api.http.HttpClient.download(HttpClient.kt:48)
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.UpdateManager.installVersion(UpdateManager.kt:302)
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.UpdateManager.updateMod(UpdateManager.kt:340)
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.UpdateManager.updateMod$default(UpdateManager.kt:329)
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.gui.ModProgressScreen.updateMod(ModProgressScreen.kt:137)
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.gui.ModProgressScreen.access$updateMod(ModProgressScreen.kt:39)
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.gui.ModProgressScreen$init$2.invokeSuspend(ModProgressScreen.kt:69)
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[13:13:59] [DefaultDispatcher-worker-2/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[13:13:59] [DefaultDispatcher-worker-2/ERROR]: modmanager.error.unknown.update
```
